spring.application.name=collection
server.port=8080

spring.jackson.serialization.indent-output=true

# Swagger
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.persist-authorization=true
springdoc.swagger-ui.with-credentials=true

# Disable favicon
spring.mvc.favicon.enabled=false

# Basic Auth
spring.security.user.name=admin
spring.security.user.password=secret123

# GraphQL
spring.graphql.graphiql.enabled=false
spring.graphql.graphiql.path=/graphiql
spring.graphql.schema.locations=classpath:graphql/
